import Head from 'next/head'
import Image from 'next/image'
import Hero from '@/components/Hero'
import TLDR from '@/components/TLDR'
import Features from '@/components/Features'
import Process from '@/components/Process'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dianomi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <svg className='w-full  absolute -top-12 -z-50 opacity-20'
        width='2560' height='4800'>
        <filter id='n' x='0' y='0'>
          <feTurbulence
            type='fractalNoise'
            baseFrequency='0.75'
            stitchTiles='stitch' />
        </filter>
        <rect width='2560' height='7000' filter="url(#n)" opacity='0.80' />
      </svg>
      <svg className='w-full absolute -top-12 -z-10' viewBox="0 0 1440 2233" fill="none" xmlns="http://www.w3.org/2000/svg">
        <g filter="url(#filter0_f_21_100)">
          <path d="M1498 736.54C1498 1072.58 1191 1345 812.298 1345C433.594 1345 -58 1182.32 -58 846.277C-58 510.234 460.518 41.5398 724.799 287.778C989.08 534.017 1498 400.496 1498 736.54Z" fill="#00FFC2" />
        </g>
        <g filter="url(#filter1_f_21_100)">
          <path d="M1498 929.54C1498 1265.58 1191 1538 812.298 1538C433.594 1538 -58 1375.32 -58 1039.28C-58 703.234 460.518 234.54 724.799 480.778C989.08 727.017 1498 593.496 1498 929.54Z" fill="#F5F5F5" />
        </g>
        <g filter="url(#filter2_f_21_100)">
          <path d="M1498 1260.54C1498 1596.58 1191 1869 812.298 1869C433.594 1869 -58 1706.32 -58 1370.28C-58 1034.23 460.518 565.54 724.799 811.778C989.08 1058.02 1498 924.496 1498 1260.54Z" fill="#07050F" />
        </g>
        <defs>
          <filter id="filter0_f_21_100" x="-422" y="-145" width="2284" height="1854" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix" />
            <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
            <feGaussianBlur stdDeviation="182" result="effect1_foregroundBlur_21_100" />
          </filter>
          <filter id="filter1_f_21_100" x="-422" y="48" width="2284" height="1854" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix" />
            <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
            <feGaussianBlur stdDeviation="182" result="effect1_foregroundBlur_21_100" />
          </filter>
          <filter id="filter2_f_21_100" x="-422" y="379" width="2284" height="1854" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
            <feFlood flood-opacity="0" result="BackgroundImageFix" />
            <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape" />
            <feGaussianBlur stdDeviation="182" result="effect1_foregroundBlur_21_100" />
          </filter>
        </defs>
      </svg>
      <main className="w-10/12 flex-col flex text-white mx-auto p-5">
        <Hero />
        <TLDR />
        <Features />
        <Process />
      </main>
      <div className="w-full bg-[#00ffc36f] relative">
        <Image src='/footer-bg.svg' width={1700} height={300} />
        <div className="flex flex-row justify-between absolute w-11/12 h-5/6 top-2 left-2 items-center">
          <h1 className='ml-10 font-Sora font-bold text-5xl'>Create.  Explore.<br />Expand.  Conquer.</h1>
          <Link href='/register' className='p-4 text-lg font-semibold bg-black text-white '>JOIN THE CLUB</Link>
        </div>
      </div>
    </div>
  )
}
