import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import Hero from '@/components/Hero'
import TLDR from '@/components/TLDR'
import Features from '@/components/Features'
import Process from '@/components/Process'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#07050F] w-11/12 flex-col flex text-white mx-auto p-5">
        <Hero />
        <TLDR />
        <Features />
        <Process />
        {/* <div className='absolute w-full h-[1126px] blur-[182px] top-[219px] backdrop-blur-[182px] bg-[#00FFC2]'></div>
        <div className='absolute w-full h-[1126px] blur-[182px] top-[438px]  bg-[#F5F5F5]'></div>
        <div className='absolute w-full h-[1126px] blur-[182px] top-[657px]  bg-[#07050F]'></div>
        <div className="absolute w-full h-[1126px] blur-[182px] top-[5968px] bg-[#00ffc2] "></div>
        <div className="absolute w-full h-[1126px] blur-[182px] top-[5749px] bg-[#F5F5F5] "></div>
        <div className="absolute w-full h-[1126px] blur-[182px] top-[5530px] bg-[#07050F] "></div> */}
      </main>
    </>
  )
}
